name: Deploy to Shared Hosting

on:
  push:
    branches: [ main ]  # Ili master, ovisno o vašoj glavnoj grani
  workflow_dispatch:    # Ovo omogućava ručno pokretanje deploymenta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build
      run: npm run build
      env:
        # Ovdje možete dodati potrebne environment varijable
        NODE_ENV: production
        
    - name: Deploy to shared hosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./out/  # Za statički export
        # Ako ne koristite statički export, promijenite u .next/
        server-dir: school-website/  # Prilagodite prema vašem hostingu
